#!/usr/bin/env bash
# Interaktives Setup nach `git clone` + `npm install`.
# Schreibt .env.local, linkt Vercel + Supabase, registriert Kuma-Monitor.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"

echo ""
echo "🛠️  AI Coding Starter Kit — Bootstrap"
echo ""

# ---------- 1. Projektname ----------
default_name="$(basename "$ROOT")"
read -rp "Projektname [$default_name]: " project_name
project_name="${project_name:-$default_name}"

# package.json#name synchronisieren — wird von kuma-register.ts via
# npm_package_name gelesen und als Monitor-Name-Prefix genutzt.
if [ -f "$ROOT/package.json" ]; then
  node -e "const fs=require('fs');const p='$ROOT/package.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));if(j.name!=='$project_name'){j.name='$project_name';fs.writeFileSync(p,JSON.stringify(j,null,2)+'\n');console.log('✅ package.json#name = $project_name');}"
fi

# ---------- 2. .env.local existiert? ----------
if [ -f "$ENV_FILE" ]; then
  read -rp ".env.local existiert. Überschreiben? [y/N]: " overwrite
  if [[ ! "$overwrite" =~ ^[yY]$ ]]; then
    echo "Skip: .env.local"
    SKIP_ENV=1
  fi
fi

if [ -z "${SKIP_ENV:-}" ]; then
  echo ""
  echo "ℹ️  Hinweis: Bei Secret-Prompts (Service-Role-Key, PostHog-Key, Kuma-Password)"
  echo "   wird die Eingabe NICHT angezeigt (Sicherheits-Feature). Einmal pasten +"
  echo "   Enter — NICHT doppelt einfügen, sonst werden die Werte aneinandergehängt."
  echo ""
  echo "── Supabase ──"
  read -rp "NEXT_PUBLIC_SUPABASE_URL: " supa_url
  read -rp "NEXT_PUBLIC_SUPABASE_ANON_KEY: " supa_anon
  read -rsp "SUPABASE_SERVICE_ROLE_KEY: " supa_service
  echo ""

  echo ""
  echo "── PostHog ──"
  read -rp "NEXT_PUBLIC_POSTHOG_KEY (phc_…): " ph_key
  read -rsp "POSTHOG_PERSONAL_API_KEY (phx_…) — Enter zum Skip: " ph_personal
  echo ""
  read -rp "POSTHOG_PROJECT_ID — Enter zum Skip: " ph_project

  echo ""
  echo "── Uptime Kuma (optional, Socket.io-Login) ──"
  read -rp "KUMA_BASE_URL — Enter zum Skip: " kuma_url
  KUMA_USER=""
  KUMA_PW=""
  KUMA_NOTIFY=""
  KUMA_PAGE_SLUG=""
  KUMA_PAGE_GROUP=""
  if [ -n "$kuma_url" ]; then
    read -rp "KUMA_USERNAME: " KUMA_USER
    read -rsp "KUMA_PASSWORD: " KUMA_PW
    echo ""
    read -rp "KUMA_NOTIFICATION_NAMES (Komma-Liste) [Intranet]: " KUMA_NOTIFY
    KUMA_NOTIFY="${KUMA_NOTIFY:-Intranet}"
    read -rp "KUMA_STATUS_PAGE_SLUG (Status-Page für automatische Gruppierung) [intranet]: " KUMA_PAGE_SLUG
    KUMA_PAGE_SLUG="${KUMA_PAGE_SLUG:-intranet}"
    read -rp "KUMA_STATUS_PAGE_GROUP (Gruppen-Name) [$project_name]: " KUMA_PAGE_GROUP
    KUMA_PAGE_GROUP="${KUMA_PAGE_GROUP:-$project_name}"
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap.sh
NEXT_PUBLIC_SUPABASE_URL=$supa_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$supa_anon
SUPABASE_SERVICE_ROLE_KEY=$supa_service

NEXT_PUBLIC_POSTHOG_KEY=$ph_key
NEXT_PUBLIC_POSTHOG_HOST=/ingest
POSTHOG_PERSONAL_API_KEY=$ph_personal
POSTHOG_PROJECT_ID=$ph_project

KUMA_BASE_URL=$kuma_url
KUMA_USERNAME=$KUMA_USER
KUMA_PASSWORD=$KUMA_PW
KUMA_NOTIFICATION_NAMES=$KUMA_NOTIFY
KUMA_STATUS_PAGE_SLUG=$KUMA_PAGE_SLUG
KUMA_STATUS_PAGE_GROUP=$KUMA_PAGE_GROUP

NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF
  echo "✅ .env.local geschrieben"
fi

# ---------- 3. Vercel-Linking ----------
echo ""
read -rp "Mit Vercel-Projekt verknüpfen jetzt? [y/N]: " vercel_link
if [[ "$vercel_link" =~ ^[yY]$ ]]; then
  if ! command -v vercel >/dev/null 2>&1; then
    echo "ℹ️  Vercel-CLI nicht gefunden. Install: npm i -g vercel"
  else
    vercel link
    vercel env pull .env.local
    echo "✅ Vercel verknüpft + Env gepullt"
  fi
fi

# ---------- 4. Supabase-Migrations ----------
echo ""
read -rp "Baseline-Migrations (profiles + rate_limit) jetzt anwenden? [y/N]: " run_migrations
if [[ "$run_migrations" =~ ^[yY]$ ]]; then
  if ! command -v supabase >/dev/null 2>&1; then
    echo "ℹ️  Supabase-CLI nicht gefunden. Install: npm i -g supabase"
  else
    supabase link --project-ref "$(echo "$supa_url" | sed -E 's|https://([^.]+).*|\1|')"
    supabase db push
    echo "✅ Migrations angewendet"
  fi
fi

# ---------- 5. Kuma-Monitor ----------
if [ -n "${kuma_url:-}" ] && [ -n "${KUMA_USER:-}" ]; then
  echo ""
  read -rp "Health-Monitor in Kuma anlegen? [y/N]: " kuma_register
  if [[ "$kuma_register" =~ ^[yY]$ ]]; then
    npm run kuma:register
  fi
fi

echo ""
echo "🎉 Fertig. Nächste Schritte:"
echo "   npm run dev"
echo "   claude → /init <idee>"
echo ""
